In [1]:
import tushare as ts
import time 
from datetime import datetime
from datetime import timedelta
import sqlite3

In [2]:
pro = ts.pro_api("d36fa5e4eb44cf289b10dbbb9a511e20ad779ae6afd6ba59a8953b19")

In [9]:
df = pro.major_news(src='', start_date='2018-11-21 00:00:00', end_date='2018-11-22 00:00:00', fields='title,content')

In [10]:
print(len(df))
df.tail()

60

,title,content
55,华夏基金管理有限公司公告（系列）,根据华夏基金管理有限公司（以下简称“本公司”）与开源证券股份有限公司（以下简称“开源证券”）...
56,云南旅游股份有限公司关于董事减持间接持有股份进展公告,董事杨建国先生保证向本公司提供的信息内容真实、准确、完整，没有虚假记载、误导性陈述或重大遗漏...
57,密尔克卫化工供应链服务股份有限公司关于全资子公司名称及经营范围变更的公告,本公司董事会及全体董事保证本公告内容不存在任何虚假记载、误导性陈述或者重大遗漏，并对其内容的...
58,广发基金管理有限公司公告（系列）,"为满足广大投资者的理财需求,广发基金管理有限公司(以下简称“本公司”)决定从2018年11月..."
59,江苏太平洋石英股份有限公司关于使用部分自有资金购买理财产品进展的公告,本公司董事会及全体董事保证本公告内容不存在任何虚假记载、误导性陈述或者重大遗漏，并对其内容的...

'\u3000\u3000盒马鲜生“标签门”侵犯了谁？\n\u3000\u3000标签门发生后，盒马鲜生称将为每个门店招募2名监督员监督门店；律师称更换标签侵犯了消费者知情权。\n\n\u3000\u3000▲盒马鲜生门店 新京报记者梁辰/摄\n\u3000\u3000作者  梁辰 陆一夫 实习生 程子姣\n\u3000\u3000编辑  陈莉 陈维城\n\u3000\u3000盒马鲜生“标签门”持续发酵。11月21日，针对员工给胡萝卜商品更换新日期标签一事，盒马鲜生CEO侯毅通过微博宣布，就地免去上海区总经理职务。但并未点出该总经理的名字。同时侯毅向盒马用户道歉。他表示，“已经开始在所有门店开展自查，进一步完善操作标准”，接下来将针对有违“客户第一”的行为，执行严厉处罚。\n\u3000\u3000对此，中国电子商务研究中心特约研究员、上海亿达律师事务所律师董毅智认为，经营者明知已经过期进行更改日期，侵犯了消费者的知情权，属于欺诈行为，消费者可以向消保委、食药监进行投诉，或是要求经营者赔偿。\n\u3000\u3000中国食品产业分析师朱丹蓬向记者表示，价签的监管只是超市管理流程中的一个步骤，真正重要的是质量内控体系的建立，以及企业主体对食品安全健康的重视程度。\n\u3000\u3000?\n\u3000\u3000静安区市场监管局拟对盒马欺诈行为按规处罚\n\u3000\u3000“标签门”事发在6天前，11月15日，有消费者在盒马鲜生上海区大宁店挑选货品时，看见一旁工作人员正在更换崇明胡萝卜外包装的日期标签，而新标签日期与原有不一致。以“11月15日”替换了9日、10日和11日的标签，相比原先的标签最多晚了6天。该消费者向上海市静安区市场监管局举报。\n\u3000\u3000有媒体报道称，该门店经理曾对消费者表示，涉事员工为外聘第三方，且没有意识到日期的差别，愿意赔付1000元现金，希望撤销投诉，未果。市场监管局立案调查发现，相关产品已销售107盒，库存剩余73盒。执法人员当即要求下架封存所有自制标签的涉事产品。\n\u3000\u300011月19日，上海市静安区市场监管局回应，已对事件立案调查，并对盒马所有产品标签进行检查。\n\u3000\u3000记者从静安区市场监管局获得一份关于“盒马鲜生虚假标签事件后续处置情况”的文件。文件显示，11月16日，静安区市场监管局接到举报后已对上海盒马网络科技有限公司静安第二分公司进行立案调查。\n\u3000\u3000根据目前查实情况，静安区市场监管局称，对其以欺诈手段提供商品，侵害消费者合法权益的行为，拟按照《上海市消费者权益保护条例》第64条第一款第一项的规定进行处罚。\n\u3000\u3000记者查询该条例发现，第64条规定，已有规定的，依照法律、法规的规定执行；法律、法规未作规定的，由工商行政管理部门责令改正，并可以根据情节单处或者并处警告、没收违法所得、处以违法所得三倍以上五倍以下的罚款，没有违法所得或者违法所得无法计算的，处以十万元以下的罚款；情节严重的，责令停业整顿。\n\u3000\u3000?\n\u3000\u3000侯毅致歉：所有门店开展自查，招募公众监督员\n\u3000\u300011月21日，针对员工给胡萝卜商品更换新日期标签一事，盒马鲜生CEO侯毅通过微博宣布，就地免去上海区总经理职务。但并未点出该总经理的名字。\n\u3000\u3000侯毅宣布上述决定的同时，对盒马用户道歉。他表示，“已经开始在所有门店开展自查，进一步完善操作标准”，接下来将针对有违“客户第一”的行为，执行严厉处罚。侯毅还宣布，将招募消费者担任服务检查员。\n\u3000\u300011月21日下午，阿里巴巴方面向记者提供的资料显示，“标签门”事件后，盒马发布了监督员招募信息，并称公众成为监督员后，可以通过直达通道向CEO团队反馈。据悉，盒马将为每个门店招募2名监督员，监督员每周要完成不少于2次门店监督。\n\u3000\u3000征集启动后2小时后，盒马已收到近100份报名邮件。盒马方面称，监督员只是盒马自查完善标准的改进措施之一，公司营运团队正在对操作标准进行修订，将尽快对全国所有门店进行培训，由店长负责执行到位。\n\u3000\u3000有知情人士告诉记者，盒马鲜生计划拓展社区超市业态，计划将“日日鲜”自有品牌商品独立运营为类菜市场模式，而且早期不会以盒马的名义进行。不过，该人士还表示，一切还有很大变数。\n\u3000\u3000对此，盒马鲜生官方回复新京报记者称，不予置评。\n\u3000\u3000?\n\u3000\u3000故意更改标签日期侵犯了消费者知情权\n\u3000\u3000替换日期标签是否已成商超常态？中国电子商务研究中心特约研究员、上海亿达律师事务所律师董毅智认为盒马员工替换日期标签这件事映射出的是商超环境里的常态。\n\u3000\u3000更换虚假生产日期的行为一直都没有消失过。据了解，2012年就有媒体曝出超市里的过期清美豆制品被替换了新包装、打上新标签，而相关裁判文书在近三年也有上千篇。2016年，联华超市因频繁出现两个日期被法院以违反食安法判决十倍赔偿；济南经十路大润发商业有限公司2017年也有因销售标注虚假生产日期的食品，被食药部门累计罚款13万元。\n\u3000\u3000经营者明知已经过期进行更改日期，董毅智律师认为，这侵犯了消费者的知情权，属于欺诈行为，消费者可以向消保委、食药监进行投诉，或是依据《食品安全法》第一百四十八条规定，要求经营者赔偿损失并支付十倍价款或三倍损失的赔偿金。商家也将面临行政处罚或是消费者维权诉讼。\n\u3000\u3000?\n\u3000\u3000品控、管理、机制都跟上，才能体现新零售的“新”\n\u3000\u3000电商研究中心主任曹磊告诉记者，生鲜电商是最难突破的瓶颈，因为物流成本高、地区差异性大、传统供应链复杂等。网购在社会零售比例超过20%，但生鲜电商在生鲜行业渗透率只有4%-5%。一方面说明这有难度，另一方面说明商业价值大。商超行业走过的坑，盒马也可能会经历，只有各方面品控、管理、机制都跟上，才能体现新零售的“新”，而不只是营销手段或者店面陈设。\n\u3000\u3000中国食品产业分析师朱丹蓬向记者表示，价签的监管只是超市管理流程中的一个步骤，真正重要的是质量内控体系的建立，以及企业主体对食品安全健康的重视程度。其认为，盒马鲜生此次“标签门”事件，实际上是利益作祟。“在店长负责制下，店长需要对整个门店的营收、利润负全责，这个KPI与门店的成本是否可控高度相关。不管是哪一种零售业态，负责人的KPI都需要根据市场变化来决定，而不能单一以利润为指标。”\n\u3000\u3000某连锁大型超市相关负责人向记者表示，一般超市由员工打价签，需先改价申请、再系统输入、最后打价签，这个过程存在时间差异、输入差异和遗漏的隐患。\n\u3000\u3000?\n\u3000\u3000盒马称日日鲜当日下架的蔬菜入垃圾清理车销毁\n\u3000\u300011月21日，新京报记者走访盒马北京门店发现，盒马蔬菜中只有部分绿叶蔬菜和少量切好的瓜类蔬菜在日日鲜专用货架上架，日日鲜为盒马自有品牌，具体售卖物品品类包括肉、蛋、豆腐和蔬菜。\n\u3000\u3000产品外包装上印星期几的字眼，与纸质标签相同。产品标签显示、日日鲜供货商与北京地理位置相近，对产地、生产日期和包装日期有明确标注，通常包装比生产晚一天，且与上市日期相同。\n\u3000\u3000盒马鲜生工作人员声称，日日鲜货品只在上架当天售卖，不会隔夜，逾期商品将下架处理，例如，下架肉类将拿来做员工餐，日日鲜当日下架的蔬菜会直接送入垃圾清理车销毁。\n\u3000\u3000据上海静安区市场监管局21日向新京报记者回应，此前上海换签事件中的胡萝卜并非为盒马鲜生日日鲜品牌。记者11月21日观察到，盒马鲜生乐成店的优选胡萝卜的分装（上架）日期为11月19日，盒马鲜生工作人员向记者透露，非日日鲜品牌的蔬菜水果等商品并不会标明下架日期，普通水果一般会放置10天，蔬菜不定期，工作人员会在合理时间对过期的蔬菜水果进行下架。\n责任编辑：李锋'

In [5]:
df = pro.cctv_news(date='20181211')

In [6]:
df.head()

,date,title,content
0,20181211,《习近平谈“一带一路”》出版发行,中共中央党史和文献研究院编辑的《习近平谈“一带一路”》一书，已由中央文献出版社出版，即日起在...
1,20181211,【在习近平新时代中国特色社会主义思想指引下——新时代 新作为 新篇章】北京“吹哨报到”：高效...,习近平总书记视察北京时强调，要坚持人民城市为人民，以北京市民最关心的问题为导向，对大气污染、...
2,20181211,汪洋率中央代表团一分团在南宁看望慰问各族干部群众,中共中央政治局常委、全国政协主席、中央代表团团长汪洋，11日率中央代表团一分团在南宁看望慰问...
3,20181211,国务院办公厅印发《关于国家综合性消防救援车辆悬挂应急救援专用号牌有关事项的通知》,近日，国务院办公厅印发《关于国家综合性消防救援车辆悬挂应急救援专用号牌有关事项的通知》，对应...
4,20181211,【数说改革开放40年】全方位开放新格局逐步形成,改革开放40年，我国对外贸易实现历史性跨越，外商投资环境持续改善，对外投资合作深入推进。今天...

In [7]:
UZviv   23

In [9]:
origin_date = datetime(2012, 11, 25)
while origin_date < datetime.now():
    origin_date += timedelta(days=1)
    try:
        str_date = origin_date.strftime('%Y%m%d')
        df = pro.cctv_news(date=str_date)
        for i in range(len(df)):
            date, title, content = df.iloc[i]
            sql = """insert into raw_data (_date, title, content) values ("{}", "{}", "{}") ;""".format(date, title, content)
            c.execute(sql)
            conn.commit()
    except Exception as e:
        print(e)
    if origin_date.day % 5 == 0:
        print(origin_date)
    time.sleep(6)

2012-11-30 00:00:00
2012-12-05 00:00:00
2012-12-10 00:00:00
2012-12-15 00:00:00
2012-12-20 00:00:00
2012-12-25 00:00:00
2012-12-30 00:00:00
2013-01-05 00:00:00
2013-01-10 00:00:00
2013-01-15 00:00:00
2013-01-20 00:00:00
2013-01-25 00:00:00
2013-01-30 00:00:00
2013-02-05 00:00:00
2013-02-10 00:00:00
2013-02-15 00:00:00
2013-02-20 00:00:00
2013-02-25 00:00:00
2013-03-05 00:00:00
2013-03-10 00:00:00
2013-03-15 00:00:00
2013-03-20 00:00:00
2013-03-25 00:00:00
2013-03-30 00:00:00
2013-04-05 00:00:00
2013-04-10 00:00:00
2013-04-15 00:00:00
2013-04-20 00:00:00
2013-04-25 00:00:00
2013-04-30 00:00:00
2013-05-05 00:00:00
2013-05-10 00:00:00
2013-05-15 00:00:00
2013-05-20 00:00:00
2013-05-25 00:00:00
2013-05-30 00:00:00
2013-06-05 00:00:00
2013-06-10 00:00:00
2013-06-15 00:00:00
2013-06-20 00:00:00
2013-06-25 00:00:00
2013-06-30 00:00:00
2013-07-05 00:00:00
2013-07-10 00:00:00
2013-07-15 00:00:00
2013-07-20 00:00:00
2013-07-25 00:00:00
2013-07-30 00:00:00
2013-08-05 00:00:00
2013-08-10 00:00:00
2013-08-15 00:00:00
2013-08-20 00:00:00
2013-08-25 00:00:00
2013-08-30 00:00:00
2013-09-05 00:00:00
2013-09-10 00:00:00
2013-09-15 00:00:00
2013-09-20 00:00:00
2013-09-25 00:00:00
2013-09-30 00:00:00
2013-10-05 00:00:00
2013-10-10 00:00:00
2013-10-15 00:00:00
2013-10-20 00:00:00
2013-10-25 00:00:00
2013-10-30 00:00:00
2013-11-05 00:00:00
2013-11-10 00:00:00
2013-11-15 00:00:00
2013-11-20 00:00:00
2013-11-25 00:00:00
2013-11-30 00:00:00
2013-12-05 00:00:00
2013-12-10 00:00:00
2013-12-15 00:00:00
2013-12-20 00:00:00
2013-12-25 00:00:00
2013-12-30 00:00:00
2014-01-05 00:00:00
2014-01-10 00:00:00
2014-01-15 00:00:00
2014-01-20 00:00:00
2014-01-25 00:00:00
2014-01-30 00:00:00
2014-02-05 00:00:00
2014-02-10 00:00:00
near "中国之家": syntax error
2014-02-15 00:00:00
2014-02-20 00:00:00
2014-02-25 00:00:00
2014-03-05 00:00:00
2014-03-10 00:00:00
2014-03-15 00:00:00
2014-03-20 00:00:00
2014-03-25 00:00:00
2014-03-30 00:00:00
2014-04-05 00:00:00
2014-04-10 00:00:00
2014-04-15 00:00:00
2014-04-20 00:00:00
near "岁月": syntax error
2014-04-25 00:00:00
2014-04-30 00:00:00
2014-05-05 00:00:00
2014-05-10 00:00:00
2014-05-15 00:00:00
2014-05-20 00:00:00
2014-05-25 00:00:00
2014-05-30 00:00:00
2014-06-05 00:00:00
2014-06-10 00:00:00
2014-06-15 00:00:00
2014-06-20 00:00:00
2014-06-25 00:00:00
2014-06-30 00:00:00
2014-07-05 00:00:00
2014-07-10 00:00:00
2014-07-15 00:00:00
2014-07-20 00:00:00
2014-07-25 00:00:00
2014-07-30 00:00:00
2014-08-05 00:00:00
2014-08-10 00:00:00
2014-08-15 00:00:00
2014-08-20 00:00:00
2014-08-25 00:00:00
2014-08-30 00:00:00
2014-09-05 00:00:00
2014-09-10 00:00:00
2014-09-15 00:00:00
2014-09-20 00:00:00
2014-09-25 00:00:00
2014-09-30 00:00:00
2014-10-05 00:00:00
2014-10-10 00:00:00
2014-10-15 00:00:00
2014-10-20 00:00:00
near "河野谈话": syntax error
2014-10-25 00:00:00
2014-10-30 00:00:00
2014-11-05 00:00:00
2014-11-10 00:00:00
2014-11-15 00:00:00
2014-11-20 00:00:00
2014-11-25 00:00:00
2014-11-30 00:00:00
2014-12-05 00:00:00
2014-12-10 00:00:00
2014-12-15 00:00:00
2014-12-20 00:00:00
2014-12-25 00:00:00
2014-12-30 00:00:00
2015-01-05 00:00:00
2015-01-10 00:00:00
2015-01-15 00:00:00
2015-01-20 00:00:00
2015-01-25 00:00:00
2015-01-30 00:00:00
2015-02-05 00:00:00
2015-02-10 00:00:00
2015-02-15 00:00:00
2015-02-20 00:00:00
2015-02-25 00:00:00
2015-03-05 00:00:00
2015-03-10 00:00:00
2015-03-15 00:00:00
2015-03-20 00:00:00
2015-03-25 00:00:00
2015-03-30 00:00:00
2015-04-05 00:00:00
2015-04-10 00:00:00
2015-04-15 00:00:00
2015-04-20 00:00:00
2015-04-25 00:00:00
2015-04-30 00:00:00
near "格雷案": syntax error
2015-05-05 00:00:00
2015-05-10 00:00:00
2015-05-15 00:00:00
2015-05-20 00:00:00
2015-05-25 00:00:00
near "支恐": syntax error
2015-05-30 00:00:00
2015-06-05 00:00:00
2015-06-10 00:00:00
2015-06-15 00:00:00
2015-06-20 00:00:00
2015-06-25 00:00:00
2015-06-30 00:00:00
2015-07-05 00:00:00
2015-07-10 00:00:00
2015-07-15 00:00:00
2015-07-20 00:00:00
2015-07-25 00:00:00
2015-07-30 00:00:00
2015-08-05 00:00:00
2015-08-10 00:00:00
2015-08-15 00:00:00
2015-08-20 00:00:00
2015-08-25 00:00:00
2015-08-30 00:00:00
2015-09-05 00:00:00
2015-09-10 00:00:00
2015-09-15 00:00:00
2015-09-20 00:00:00
2015-09-25 00:00:00
2015-09-30 00:00:00
2015-10-05 00:00:00
2015-10-10 00:00:00
2015-10-15 00:00:00
2015-10-20 00:00:00
near "帕特里夏": syntax error
2015-10-25 00:00:00
2015-10-30 00:00:00
2015-11-05 00:00:00
2015-11-10 00:00:00
near "产业发展新引擎": syntax error
2015-11-15 00:00:00
2015-11-20 00:00:00
2015-11-25 00:00:00
2015-11-30 00:00:00
2015-12-05 00:00:00
2015-12-10 00:00:00
2015-12-15 00:00:00
2015-12-20 00:00:00
2015-12-25 00:00:00
2015-12-30 00:00:00
2016-01-05 00:00:00
2016-01-10 00:00:00
2016-01-15 00:00:00
2016-01-20 00:00:00
2016-01-25 00:00:00
2016-01-30 00:00:00
2016-02-05 00:00:00
2016-02-10 00:00:00
2016-02-15 00:00:00
2016-02-20 00:00:00
2016-02-25 00:00:00
2016-03-05 00:00:00
2016-03-10 00:00:00
2016-03-15 00:00:00
2016-03-20 00:00:00
2016-03-25 00:00:00
2016-03-30 00:00:00
2016-04-05 00:00:00
2016-04-10 00:00:00
2016-04-15 00:00:00
2016-04-20 00:00:00
2016-04-25 00:00:00
2016-04-30 00:00:00
2016-05-05 00:00:00
2016-05-10 00:00:00
2016-05-15 00:00:00
2016-05-20 00:00:00
2016-05-25 00:00:00
2016-05-30 00:00:00
2016-06-05 00:00:00
2016-06-10 00:00:00
2016-06-15 00:00:00
2016-06-20 00:00:00
2016-06-25 00:00:00
2016-06-30 00:00:00
2016-07-05 00:00:00
2016-07-10 00:00:00
2016-07-15 00:00:00
2016-07-20 00:00:00
2016-07-25 00:00:00
2016-07-30 00:00:00
2016-08-05 00:00:00
2016-08-10 00:00:00
2016-08-15 00:00:00
near "撑竿跳女皇": syntax error
2016-08-20 00:00:00
2016-08-25 00:00:00
2016-08-30 00:00:00
2016-09-05 00:00:00
2016-09-10 00:00:00
2016-09-15 00:00:00
2016-09-20 00:00:00
2016-09-25 00:00:00
2016-09-30 00:00:00
near "萨德": syntax error
2016-10-05 00:00:00
2016-10-10 00:00:00
2016-10-15 00:00:00
2016-10-20 00:00:00
2016-10-25 00:00:00
2016-10-30 00:00:00
2016-11-05 00:00:00
2016-11-10 00:00:00
2016-11-15 00:00:00
2016-11-20 00:00:00
2016-11-25 00:00:00
2016-11-30 00:00:00
2016-12-05 00:00:00
2016-12-10 00:00:00
2016-12-15 00:00:00
2016-12-20 00:00:00
2016-12-25 00:00:00
2016-12-30 00:00:00
2017-01-05 00:00:00
2017-01-10 00:00:00
2017-01-15 00:00:00
2017-01-20 00:00:00
2017-01-25 00:00:00
2017-01-30 00:00:00
near "禁穆令": syntax error
2017-02-05 00:00:00
2017-02-10 00:00:00
2017-02-15 00:00:00
2017-02-20 00:00:00
2017-02-25 00:00:00
2017-03-05 00:00:00
2017-03-10 00:00:00
2017-03-15 00:00:00
2017-03-20 00:00:00
2017-03-25 00:00:00
2017-03-30 00:00:00
2017-04-05 00:00:00
2017-04-10 00:00:00
2017-04-15 00:00:00
2017-04-20 00:00:00
2017-04-25 00:00:00
near "脱欧": syntax error
2017-04-30 00:00:00
2017-05-05 00:00:00
2017-05-10 00:00:00
2017-05-15 00:00:00
2017-05-20 00:00:00
2017-05-25 00:00:00
2017-05-30 00:00:00
2017-06-05 00:00:00
2017-06-10 00:00:00
2017-06-15 00:00:00
2017-06-20 00:00:00
2017-06-25 00:00:00
2017-06-30 00:00:00
2017-07-05 00:00:00
2017-07-10 00:00:00
2017-07-15 00:00:00
2017-07-20 00:00:00
2017-07-25 00:00:00
2017-07-30 00:00:00
2017-08-05 00:00:00
2017-08-10 00:00:00
2017-08-15 00:00:00
2017-08-20 00:00:00
2017-08-25 00:00:00
2017-08-30 00:00:00
2017-09-05 00:00:00
2017-09-10 00:00:00
2017-09-15 00:00:00
2017-09-20 00:00:00
2017-09-25 00:00:00
2017-09-30 00:00:00
2017-10-05 00:00:00
2017-10-10 00:00:00
2017-10-15 00:00:00
2017-10-20 00:00:00
2017-10-25 00:00:00
2017-10-30 00:00:00
2017-11-05 00:00:00
2017-11-10 00:00:00
2017-11-15 00:00:00
2017-11-20 00:00:00
2017-11-25 00:00:00
2017-11-30 00:00:00
2017-12-05 00:00:00
2017-12-10 00:00:00
2017-12-15 00:00:00
2017-12-20 00:00:00
2017-12-25 00:00:00
2017-12-30 00:00:00
2018-01-05 00:00:00
2018-01-10 00:00:00
2018-01-15 00:00:00
2018-01-20 00:00:00
2018-01-25 00:00:00
2018-01-30 00:00:00
2018-02-05 00:00:00
2018-02-10 00:00:00
2018-02-15 00:00:00
2018-02-20 00:00:00
2018-02-25 00:00:00
2018-03-05 00:00:00
2018-03-10 00:00:00
2018-03-15 00:00:00
2018-03-20 00:00:00
2018-03-25 00:00:00
2018-03-30 00:00:00
2018-04-05 00:00:00
2018-04-10 00:00:00
2018-04-15 00:00:00
2018-04-20 00:00:00
2018-04-25 00:00:00
2018-04-30 00:00:00
2018-05-05 00:00:00
2018-05-10 00:00:00
2018-05-15 00:00:00
2018-05-20 00:00:00
2018-05-25 00:00:00
2018-05-30 00:00:00
2018-06-05 00:00:00
2018-06-10 00:00:00
2018-06-15 00:00:00
2018-06-20 00:00:00
2018-06-25 00:00:00

2018-06-30 00:00:00
2018-07-05 00:00:00
2018-07-10 00:00:00
2018-07-15 00:00:00
2018-07-20 00:00:00
2018-07-25 00:00:00
2018-07-30 00:00:00
2018-08-05 00:00:00
2018-08-10 00:00:00
2018-08-15 00:00:00
2018-08-20 00:00:00
2018-08-25 00:00:00
2018-08-30 00:00:00
2018-09-05 00:00:00
2018-09-10 00:00:00
2018-09-15 00:00:00
2018-09-20 00:00:00
2018-09-25 00:00:00
2018-09-30 00:00:00
2018-10-05 00:00:00
2018-10-10 00:00:00
2018-10-15 00:00:00
2018-10-20 00:00:00
2018-10-25 00:00:00
2018-10-30 00:00:00
2018-11-05 00:00:00
2018-11-10 00:00:00
2018-11-15 00:00:00
2018-11-20 00:00:00
2018-11-25 00:00:00
2018-11-30 00:00:00
2018-12-05 00:00:00
2018-12-10 00:00:00
2018-12-15 00:00:00
2018-12-20 00:00:00
2018-12-25 00:00:00
2018-12-30 00:00:00
2019-01-05 00:00:00
2019-01-10 00:00:00
系统内部错误
2019-01-15 00:00:00
2019-01-20 00:00:00
2019-01-25 00:00:00

In [82]:
df = pro.income()

ConnectionError: HTTPConnectionPool(host='api.tushare.pro', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x116e04b00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

In [79]:
df.h

,ts_code,ann_date,f_ann_date,end_date,report_type,comp_type,basic_eps,diluted_eps,total_revenue,revenue,...,minority_gain,oth_compr_income,t_compr_income,compr_inc_attr_p,compr_inc_attr_m_s,ebit,ebitda,insurance_exp,undist_profit,distable_profit
0,600000.SH,20180830,20180830,20180630,1,2,0.950,0.950,8.225600e+10,8.225600e+10,...,3.310000e+08,2.719000e+09,3.161900e+10,3.128600e+10,3.330000e+08,6.135500e+10,6.284600e+10,None,NaN,NaN
1,600000.SH,20180428,20180428,20180331,1,2,0.460,0.460,3.962900e+10,3.962900e+10,...,1.540000e+08,1.398000e+09,1.585700e+10,1.570900e+10,1.480000e+08,2.927800e+10,NaN,None,NaN,NaN
2,600000.SH,20180428,20180428,20171231,1,2,1.840,1.840,1.686190e+11,1.686190e+11,...,7.440000e+08,-5.572000e+09,4.943000e+10,4.869000e+10,7.400000e+08,1.259620e+11,1.288950e+11,None,NaN,NaN
3,600000.SH,20171028,20171028,20170930,1,2,1.450,1.450,1.247680e+11,1.247680e+11,...,5.040000e+08,-2.151000e+09,4.024500e+10,3.974400e+10,5.010000e+08,NaN,NaN,None,NaN,NaN
4,600000.SH,20170830,20170830,20170630,1,2,0.970,0.970,8.335400e+10,8.335400e+10,...,3.570000e+08,-3.985000e+09,2.453700e+10,2.418100e+10,3.560000e+08,-5.516000e+09,-4.111000e+09,None,NaN,NaN
5,600000.SH,20170427,20170427,20170331,1,2,0.630,0.630,4.236000e+10,4.236000e+10,...,1.850000e+08,-1.523000e+09,1.312400e+10,1.293900e+10,1.850000e+08,NaN,NaN,None,NaN,NaN
6,600000.SH,20170401,20170401,20161231,1,2,2.404,2.404,1.607920e+11,1.607920e+11,...,5.790000e+08,-5.479000e+09,4.819900e+10,4.761900e+10,5.800000e+08,9.872000e+09,1.305600e+10,None,NaN,NaN
7,600000.SH,20161029,20161029,20160930,1,2,1.873,1.873,1.209280e+11,1.209280e+11,...,4.560000e+08,-2.099000e+09,3.903900e+10,3.858300e+10,4.560000e+08,NaN,NaN,None,NaN,NaN
8,600000.SH,20160811,20160811,20160630,1,2,1.229,1.229,8.217200e+10,8.217200e+10,...,2.700000e+08,-2.556000e+09,2.448400e+10,2.421400e+10,2.700000e+08,7.905000e+09,9.374000e+09,None,NaN,NaN
9,600000.SH,20160430,20160430,20160331,1,2,0.696,0.696,4.219100e+10,4.219100e+10,...,1.130000e+08,-1.651000e+09,1.238400e+10,1.227100e+10,1.130000e+08,3.171800e+10,NaN,None,NaN,NaN
10,600000.SH,20160407,20160407,20151231,1,2,2.665,2.665,1.465500e+11,1.465500e+11,...,3.930000e+08,4.454000e+09,5.545100e+10,5.506200e+10,3.890000e+08,-1.122000e+10,-8.992000e+09,None,NaN,NaN
11,600000.SH,20151030,20151030,20150930,1,2,1.992,1.992,1.086320e+11,1.086320e+11,...,3.130000e+08,2.095000e+09,3.957000e+10,3.925700e+10,3.130000e+08,7.931100e+10,NaN,None,NaN,NaN
12,600000.SH,20150820,20150820,20150630,1,2,1.281,1.281,7.070100e+10,7.070100e+10,...,2.230000e+08,7.850000e+08,2.491100e+10,2.468800e+10,2.230000e+08,-8.170000e+09,-7.162000e+09,None,NaN,NaN
13,600000.SH,20150430,20150430,20150331,1,2,0.600,0.600,3.299100e+10,3.299100e+10,...,1.150000e+08,-8.290000e+08,1.048000e+10,1.036500e+10,1.150000e+08,4.230400e+10,NaN,None,NaN,NaN
14,600000.SH,20150319,20150319,20141231,1,2,2.521,2.521,1.231810e+11,1.231810e+11,...,3.340000e+08,6.119000e+09,5.347900e+10,5.314500e+10,3.340000e+08,-2.824800e+10,-2.625400e+10,None,NaN,NaN
15,600000.SH,20141031,20141031,20140930,1,2,1.866,1.866,8.977300e+10,8.977300e+10,...,3.680000e+08,4.473000e+09,3.964000e+10,3.927200e+10,3.680000e+08,1.068210e+11,NaN,None,NaN,NaN
16,600000.SH,20140814,20140814,20140630,1,2,1.215,1.215,5.904300e+10,5.904300e+10,...,2.110000e+08,3.592000e+09,2.645900e+10,2.624800e+10,2.110000e+08,-1.490400e+10,-1.394000e+10,None,NaN,NaN
17,600000.SH,20140430,20140430,20140331,1,2,0.574,0.574,2.760200e+10,2.760200e+10,...,9.800000e+07,1.614000e+09,1.242200e+10,1.232400e+10,9.800000e+07,3.212700e+10,NaN,None,NaN,NaN
18,600000.SH,20140320,20140320,20131231,1,2,2.190,2.190,1.000150e+11,1.000150e+11,...,2.780000e+08,-3.835000e+09,3.736500e+10,3.708700e+10,2.780000e+08,-2.592400e+10,-2.411400e+10,None,NaN,NaN
19,600000.SH,20131031,20131031,20130930,1,2,1.599,1.599,7.247700e+10,7.247700e+10,...,1.880000e+08,-1.328000e+09,2.867800e+10,2.849000e+10,1.880000e+08,8.076900e+10,NaN,None,NaN,NaN
20,600000.SH,20130814,20130814,20130630,1,2,1.040,1.040,4.651800e+10,4.651800e+10,...,1.160000e+08,8.000000e+07,1.958200e+10,1.946600e+10,1.160000e+08,-1.351300e+10,-1.264200e+10,None,NaN,NaN
21,600000.SH,20130427,20130427,20130331,1,2,0.477,0.477,2.201100e+10,2.201100e+10,...,4.800000e+07,4.480000e+08,9.399000e+09,9.351000e+09,4.800000e+07,2.408800e+10,NaN,None,NaN,NaN
22,600000.SH,20130314,20130314,20121231,1,2,1.830,1.830,8.295200e+10,8.295200e+10,...,1.250000e+08,1.700000e+07,3.432800e+10,3.420300e+10,1.250000e+08,-2.457600e+10,-2.298600e+10,None,NaN,NaN
23,600000.SH,20121031,20121031,20120930,1,2,1.401,1.401,6.082992e+10,6.082992e+10,...,1.140760e+08,2.715040e+08,2.651138e+10,2.639731e+10,1.140760e+08,6.572809e+10,NaN,None,NaN,NaN
24,600000.SH,20120815,20120815,20120630,1,2,0.920,0.920,4.000299e+10,4.000299e+10,...,7.277800e+07,1.542155e+09,1.880792e+10,1.873514e+10,7.277800e+07,-1.336191e+10,-1.261222e+10,None,NaN,NaN
25,600000.SH,20120428,20120428,20120331,1,2,0.423,0.423,1.990886e+10,1.990886e+10,...,3.815400e+07,2.705910e+08,8.202643e+09,8.164489e+09,3.815400e+07,2.157442e+10,NaN,None,NaN,NaN
26,600000.SH,20120316,20120316,20111231,1,2,1.460,1.460,6.791767e+10,6.791767e+10,...,6.913100e+07,9.047290e+08,2.825984e+10,2.819071e+10,6.913100e+07,-1.680356e+10,-1.541120e+10,None,NaN,NaN
27,600000.SH,20111029,20111029,20110930,1,2,1.067,1.067,4.930743e+10,4.930743e+10,...,5.976820e+07,-1.043549e+09,1.892614e+10,1.886637e+10,5.976820e+07,5.302667e+10,NaN,None,NaN,NaN
28,600000.SH,20110816,20110816,20110630,1,2,0.690,0.690,3.186511e+10,3.186511e+10,...,3.116300e+07,-3.517780e+08,1.255891e+10,1.252775e+10,3.116300e+07,-5.225720e+09,-4.560194e+09,None,NaN,NaN
29,600000.SH,20110428,20110428,20110331,1,2,0.422,0.422,1.519599e+10,1.519599e+10,...,1.525910e+07,1.116100e+07,6.085140e+09,6.069881e+09,1.525910e+07,1.601479e+10,NaN,None,NaN,NaN
30,600000.SH,20110330,20110330,20101231,1,2,1.600,1.600,4.985585e+10,4.985585e+10,...,1.375748e+06,-2.009606e+09,1.716898e+10,1.716760e+10,1.375748e+06,1.755726e+09,2.998525e+09,None,NaN,NaN
31,600000.SH,20101029,20101029,20100930,1,2,1.293,1.293,3.589171e+10,3.589171e+10,...,8.123758e+06,1.354632e+08,1.498083e+10,1.497271e+10,8.123758e+06,3.796663e+10,NaN,None,NaN,NaN
32,600000.SH,20100830,20100830,20100630,1,2,0.791,0.791,2.275149e+10,2.275149e+10,...,1.837005e+06,1.731706e+08,9.255756e+09,9.253919e+09,1.837005e+06,9.132480e+08,1.517842e+09,None,NaN,NaN
33,600000.SH,20100430,20100430,20100331,1,2,0.465,0.465,1.072402e+10,1.072402e+10,...,-1.159323e+06,1.493600e+08,4.254203e+09,4.255363e+09,-1.159323e+06,1.153926e+10,NaN,None,NaN,NaN
34,600000.SH,20100407,20100407,20091231,1,2,1.620,1.620,3.682393e+10,3.682393e+10,...,-1.443886e+06,-4.675402e+08,1.274760e+10,1.274904e+10,-1.443886e+06,-6.521756e+09,-5.471803e+09,None,NaN,NaN
35,600000.SH,20091029,20091029,20090930,1,2,1.297,1.297,2.634216e+10,2.634216e+10,...,6.421118e+05,NaN,NaN,NaN,NaN,2.824498e+10,NaN,None,NaN,NaN
36,600000.SH,20090829,20090829,20090630,1,2,0.856,0.856,1.667737e+10,1.667737e+10,...,6.807228e+05,-3.494596e+08,6.431912e+09,6.431232e+09,6.807228e+05,-3.555852e+09,-3.052543e+09,None,NaN,NaN
37,600000.SH,20090430,20090430,20090331,1,2,0.523,0.523,7.902030e+09,7.902030e+09,...,2.214885e+04,NaN,NaN,NaN,NaN,9.326587e+09,NaN,None,NaN,NaN
38,600000.SH,20090410,20090410,20081231,1,2,2.210,2.211,3.456057e+10,3.456057e+10,...,-1.366228e+05,NaN,NaN,NaN,NaN,-5.616203e+09,-4.691906e+09,None,NaN,NaN
39,600000.SH,20081030,20081030,20080930,1,2,1.740,1.740,2.570744e+10,2.570744e+10,...,NaN,NaN,NaN,NaN,NaN,2.737659e+10,NaN,None,NaN,NaN
40,600000.SH,20080823,20080823,20080630,1,2,1.130,1.130,1.670613e+10,1.670613e+10,...,NaN,NaN,NaN,NaN,NaN,-2.845219e+09,-2.411382e+09,None,NaN,NaN
41,600000.SH,20080426,20080426,20080331,1,2,0.650,0.500,8.037935e+09,8.037935e+09,...,NaN,NaN,NaN,NaN,NaN,9.040975e+09,NaN,None,NaN,NaN
42,600000.SH,20080228,20080228,20071231,1,2,1.263,1.263,2.587643e+10,2.587643e+10,...,NaN,NaN,NaN,NaN,NaN,-2.625978e+08,5.166897e+08,None,NaN,NaN
43,600000.SH,20071027,20071027,20070930,1,2,0.900,0.900,1.831036e+10,1.831036e+10,...,NaN,NaN,NaN,NaN,NaN,2.093627e+10,NaN,None,NaN,NaN
44,600000.SH,20070822,20070822,20070630,1,2,0.586,0.586,1.161290e+10,1.161290e+10,...,NaN,NaN,NaN,NaN,NaN,8.607908e+08,1.230253e+09,None,NaN,NaN
45,600000.SH,20070428,20070428,20070331,1,2,0.225,0.225,5.285082e+09,5.285082e+09,...,NaN,NaN,NaN,NaN,NaN,6.706153e+09,NaN,None,1.038130e+09,2.016417e+09
46,600000.SH,20070324,20070324,20061231,1,2,0.850,0.850,1.892708e+10,1.892708e+10,...,NaN,NaN,NaN,NaN,NaN,-1.041374e+09,-3.834421e+08,None,6.899616e+08,4.042988e+09
47,600000.SH,20061026,20061027,20060930,1,2,0.570,0.570,1.343828e+10,1.343828e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,6.899616e+08,3.143500e+09
48,600000.SH,20060811,20060812,20060630,1,2,NaN,NaN,8.610547e+09,8.610547e+09,...,NaN,NaN,NaN,NaN,NaN,-4.778001e+08,-1.137914e+08,None,6.899616e+08,2.289204e+09
49,600000.SH,20060812,20060812,20060630,1,2,NaN,NaN,8.610547e+09,8.610547e+09,...,NaN,NaN,NaN,NaN,NaN,-4.778001e+08,-1.137914e+08,None,6.899616e+08,2.289204e+09
50,600000.SH,20070428,20060429,20060331,1,2,NaN,NaN,4.079680e+09,4.079680e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,6.899616e+08,1.422018e+09
51,600000.SH,20070324,20060302,20051231,1,2,NaN,NaN,1.456840e+10,1.456840e+10,...,NaN,NaN,NaN,NaN,NaN,-1.180087e+09,-6.253231e+08,None,6.691590e+08,3.227163e+09
52,600000.SH,20051029,20051029,20050930,1,2,NaN,NaN,1.565295e+10,1.565295e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
53,600000.SH,20050826,20050826,20050630,1,2,NaN,NaN,1.030396e+10,1.030396e+10,...,NaN,NaN,NaN,NaN,NaN,7.310989e+09,7.586814e+09,None,NaN,NaN
54,600000.SH,20050423,20050423,20050331,1,2,NaN,NaN,5.015332e+09,5.015332e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,5.542976e+08,1.068057e+09
55,600000.SH,20050226,20050226,20041231,1,2,NaN,NaN,1.141155e+10,1.141155e+10,...,NaN,NaN,NaN,NaN,NaN,-5.072150e+09,-4.505372e+09,None,4.839261e+08,2.413957e+09
56,600000.SH,20041030,20041030,20040930,1,2,NaN,NaN,1.212252e+10,1.212252e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
57,600000.SH,20040814,20040814,20040630,1,2,NaN,NaN,7.822997e+09,7.822997e+09,...,NaN,NaN,NaN,NaN,NaN,5.533354e+09,5.805510e+09,None,NaN,NaN
58,600000.SH,20040428,20040428,20040331,1,2,NaN,NaN,3.728987e+09,3.728987e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN
59,600000.SH,20040227,20040227,20031231,1,2,NaN,NaN,8.567363e+09,8.567363e+09,...,NaN,NaN,NaN,NaN,NaN,-3.695514e+09,-3.213554e+09,None,4.291644e+08,1.995253e+09

In [22]:
import math
w1 = 0.9
w2 = 1 - w1
r1 = 0.14216
r2 = 0.12600
v1 = 1.7267
v2 = 1.7170
rho = 0.19928
r = w1*r1 + w2*r2
print(r) 
vp2 = (w1**2)*(v1**2)+(w2**2)*(v2**2)+2*w1*w2*v1*v2*rho
print(vp2, math.sqrt(vp2))

0.140544
2.55083668049056 1.5971338956050491

In [31]:
0.075*.03**2+0.85*.015**2+0.075*0.0125**2

0.00027046875

In [32]:
math.sqrt(0.00027046875)

0.016445934147989283